pageIDs:
  personShowPid: 12
  organizationShowPid: 19
  eventShowPid: 225
  blackboardShowPid: 228
  presentShowPid: 232
  registrationShowPid: 233

persistence:
  storagePids:
    persons: 13
    blackboards: 13
    gifts: 227
    events: 21
    presents: 13

page:
  logo:
    file: EXT:leseohren/Resources/Public/Icons/logo_leseohren.svg
    fileInverted: EXT:leseohren/Resources/Public/Icons/logo_leseohren-inverted.svg
    height: 60
    width: 168
    alt: Leseohren e.V.
    linktitle: Leseohren e.V.
  theme:
    language:
      enable: false
    googleFont:
      enable: false
    cookieconsent:
      enable: false
    breadcrumb:
      enableLevel: 1
    copyright:
      enable: true
      text: '&copy; 2024 Leseohren e.V.'

plugin:
  tx_leseohren_personen:
    view:
      templateRootPath: EXT:leseohren/Resources/Private/Templates/
      partialRootPath: EXT:leseohren/Resources/Private/Partials/
      layoutRootPath: EXT:leseohren/Resources/Private/Layouts/
  tx_leseohren_organizations:
    view:
      templateRootPath: EXT:leseohren/Resources/Private/Templates/
      partialRootPath: EXT:leseohren/Resources/Private/Partials/
      layoutRootPath: EXT:leseohren/Resources/Private/Layouts/
  tx_leseohren_events:
    view:
      templateRootPath: EXT:leseohren/Resources/Private/Templates/
      partialRootPath: EXT:leseohren/Resources/Private/Partials/
      layoutRootPath: EXT:leseohren/Resources/Private/Layouts/
  tx_leseohren_blackboards:
    view:
      templateRootPath: EXT:leseohren/Resources/Private/Templates/
      partialRootPath: EXT:leseohren/Resources/Private/Partials/
      layoutRootPath: EXT:leseohren/Resources/Private/Layouts/
  tx_leseohren_persondashboard:
    view:
      templateRootPath: EXT:leseohren/Resources/Private/Templates/
      partialRootPath: EXT:leseohren/Resources/Private/Partials/
      layoutRootPath: EXT:leseohren/Resources/Private/Layouts/
  tx_leseohren_presents:
    view:
      templateRootPath: EXT:leseohren/Resources/Private/Templates/
      partialRootPath: EXT:leseohren/Resources/Private/Partials/
      layoutRootPath: EXT:leseohren/Resources/Private/Layouts/
