pageIDs:
  personShowPid: 7
  organizationShowPid: 10
  eventShowPid: 11
  blackboardShowPid: 13
  presentShowPid: 14
  registrationShowPid: 20

persistence:
  storagePids:
    persons: 9
    blackboards: 9
    gifts: 9
    events: 18
    presents: 9

page:
  logo:
    file: EXT:leseohren/Resources/Public/Icons/logo_leseohren.svg
    fileInverted: EXT:leseohren/Resources/Public/Icons/logo_leseohren-inverted.svg
    height: 60
    width: 168
    alt: Leseohren e.V.
    linktitle: Leseohren e.V.
  theme:
    language:
      enable: false
    googleFont:
      enable: false
    cookieconsent:
      enable: false
    breadcrumb:
      enableLevel: 1
    copyright:
      enable: true
      text: '&copy; 2024 Leseohren e.V.'

plugin:
  tx_leseohren_personen:
    view:
      templateRootPath: EXT:leseohren/Resources/Private/Templates/
      partialRootPath: EXT:leseohren/Resources/Private/Partials/
      layoutRootPath: EXT:leseohren/Resources/Private/Layouts/
  tx_leseohren_organizations:
    view:
      templateRootPath: EXT:leseohren/Resources/Private/Templates/
      partialRootPath: EXT:leseohren/Resources/Private/Partials/
      layoutRootPath: EXT:leseohren/Resources/Private/Layouts/
  tx_leseohren_events:
    view:
      templateRootPath: EXT:leseohren/Resources/Private/Templates/
      partialRootPath: EXT:leseohren/Resources/Private/Partials/
      layoutRootPath: EXT:leseohren/Resources/Private/Layouts/
  tx_leseohren_blackboards:
    view:
      templateRootPath: EXT:leseohren/Resources/Private/Templates/
      partialRootPath: EXT:leseohren/Resources/Private/Partials/
      layoutRootPath: EXT:leseohren/Resources/Private/Layouts/
  tx_leseohren_persondashboard:
    view:
      templateRootPath: EXT:leseohren/Resources/Private/Templates/
      partialRootPath: EXT:leseohren/Resources/Private/Partials/
      layoutRootPath: EXT:leseohren/Resources/Private/Layouts/
  tx_leseohren_presents:
    view:
      templateRootPath: EXT:leseohren/Resources/Private/Templates/
      partialRootPath: EXT:leseohren/Resources/Private/Partials/
      layoutRootPath: EXT:leseohren/Resources/Private/Layouts/
