base: '%env(SITE_BASE)%'
dependencies:
  - skom/skombase13
languages:
  -
    title: German
    enabled: true
    languageId: 0
    base: /
    locale: de_DE.utf8
    navigationTitle: Deutsch
    flag: de
    hreflang: de-DE
    websiteTitle: ''
rootPageId: 1
websiteTitle: ''
