# Inherits default site-unspecific frontend policy mutations (enabled per default)
inheritDefault: true
mutations:
  # Results in `default-src 'self'`
  - mode: set
    directive: 'default-src'
    sources:
      - "'self'"
  # thus reuses 'self' and adds additional sources
  # Results in `img-src 'self' data: *.typo3.org`
  - mode: extend
    directive: 'img-src'
    sources:
      - 'data:'
      - '*.img.youtube.com'
  # Results in `script-src 'self' 'nonce-[random]'`
  # ('nonce-proxy' is substituted when compiling the policy)
  - mode: extend
    directive: 'script-src'
    sources:
      - "'nonce-proxy'"
  - mode: extend
    directive: 'font-src'
    sources:
      - 'https://fonts.gstatic.com'
